import Head from "next/head";
import { Inter } from "@next/font/google";
import Recherche from "../components/Recherche";
import { Stack } from "@mui/material";
import axios from "axios";
import Header from "../components/Header";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ fleet }) {
    return (
        <>
            <Head>
                <title>Wild Cars</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Stack
                sx={{
                    width: "100%",
                    height: "100vh",
                    display: "flex",
                    justifyContent: "center",
                    alignItems: "center",
                    backgroundColor: "#01142B",
                }}
            >
                <Header />
                <Recherche fleet={fleet} />
            </Stack>
        </>
    );
}

export async function getServerSideProps() {
    const res = await axios.get(`/api/cars`);

    const fleet = res.data;
    return {
        props: {
            fleet,
        },
    };
}
