import Head from "next/head";
import { Inter } from "@next/font/google";
import Recherche from "../components/Recherche";
import { Stack } from "@mui/material";
import axios from "axios";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });
const ENDPOINT = process.env.DB_HOST;

export default function Home({ fleet }) {
  return (
    <>
      <Head>
        <title>Wild Cars</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        sx={{
          width: "100%",
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Header />
        <Recherche fleet={fleet} />
      </Stack>
    </>
  );
}

export async function getStaticProps() {
  const res = await axios.get(`${ENDPOINT}/api/cars`);
  const fleet = res.data.Items;
  return {
    props: {
      fleet,
    },
  };
}
